server:
  port: 8080
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
application:
  properties:
    services:
      icritic-users-service-address: ${ICRITIC_USERS_SERVICE_ADDRESS:http://localhost:8081}
      icritic-movies-service-address: ${ICRITIC_MOVIES_SERVICE_ADDRESS:http://localhost:8083}
    jwtSecret: ${ICRITIC_JWT_SECRET:b7c995a4acd856ea084449fa0000bd086d38888ecddd4d8f4b6b6805f03b028270bfcb5bc7de7c9f24fe7e8a317e633fedb2a3a4441f5af4dc7933e0ff6d7d1b}

