apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: icritic-stage-keyvault-provider
spec:
  provider: azure
  secretObjects:
    - data:
        - key: ICRITIC_JWT_SECRET
          objectName: ICRITIC-JWT-SECRET
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "59bc0c69-c7f6-4f1b-989f-5be0232b8cb5"
    keyvaultName: "icritic-stage-keyvault"
    cloudName: "AzurePublicCloud"
    objects:  |
      array:
        - |
          objectName: ICRITIC-JWT-SECRET
          objectType: secret             
          objectVersion: ""
    tenantId: ebc53480-3f79-45b4-8df1-c0824e236476